<a href="https://colab.research.google.com/github/Boyakin/qChem/blob/main/%D0%9A%D0%B2%D0%A5%D0%B8%D0%BCPractice_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install pyscf geometric

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.0/386.0 kB 5.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 MB 12.4 MB/s eta 0:00:00
  Created wheel for geometric: filename=geometric-1.1-py3-none-any.whl size=402087 sha256=e06ecafc43dd4a52c3695cf590d43132ff7809dde5165afc6dfb6000c78d7ad7
  Stored in directory: /root/.cache/pip/wheels/c5/77/0c/96a54539fe0560749fdbe283f92582d09bddb212856407a4cb
Successfully built geometric


In [ ]:
import numpy as np
from pyscf import gto, scf, fci, ci, mcscf, mp, cc, dft, tddft
from pyscf.hessian import thermo
import time

In [ ]:
rco = 1.21
rch = 1.11
ahch = 120.

geom_zmat = f'''
O
C   1   {rco}
H   2   {rch}   1   {ahch}
H   2   {rch}   1   {ahch}  3 180.
'''

In [ ]:
hcoh = gto.Mole(atom=geom_zmat, unit='Angstrom', basis='ccpvtz', charge=0, spin=0, symmetry=True)
hcoh.build()
func = 'MN15_L'
hcoh_calc = dft.RKS(hcoh, xc=func).run()
hcoh_opt_geomtric = hcoh_calc.Gradients().optimizer(solver='geomeTRIC').kernel()

converged SCF energy = -114.431947316807


geometric-optimize called with the following command line:
/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py -f /root/.local/share/jupyter/runtime/kernel-59355ebc-8522-4da2-abea-79e43ea019c1.json

                                        ())))))))))))))))/                     
                                    ())))))))))))))))))))))))),                
                                *)))))))))))))))))))))))))))))))))             
                        #,    ()))))))))/                .)))))))))),          
                      #%%%%,  ())))))                        .))))))))*        
                      *%%%%%%,  ))              ..              ,))))))).      
                        *%%%%%%,         ***************/.        .)))))))     
                #%%/      (%%%%%%,    /*********************.       )))))))    
              .%%%%%%#      *%%%%%%,  *******/,     **********,      .))))))   
                .%%%%%%/      *%%%%%%,  **              ********    


Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O   0.000000   0.000000   0.000000    0.000000  0.000000  0.000000
   C   1.210000   0.000000   0.000000    0.000000  0.000000  0.000000
   H   1.765000   0.000000   0.961288    0.000000  0.000000  0.000000
   H   1.765000  -0.000000  -0.961288    0.000000  0.000000  0.000000
converged SCF energy = -114.431947316809
--------------- SymAdaptedRKS_Scanner gradients ---------------
         x                y                z
0 O    -0.0078283262     0.0000000000    -0.0000000000
1 C     0.0245865668     0.0000000000     0.0000000000
2 H    -0.0084767259    -0.0000000000    -0.0009920315
3 H    -0.0084767259     0.0000000000     0.0009920315
----------------------------------------------
cycle 1: E = -114.431947317  dE = -114.432  norm(grad) = 0.0284861


Step    0 : Gradient = 1.424e-02/2.459e-02 (rms/max) Energy = -114.4319473168
Hessian Eigenvalues: 4.50000e-02 5.00000e-02 5.00000e-02 ... 3.26000e-01 3.26000e-01 9.99547e-01



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.017806  -0.000000  -0.020830   -0.017806 -0.000000 -0.020830
   C   1.187588  -0.000000   0.013432   -0.022412 -0.000000  0.013432
   H   1.804487  -0.000000   0.946109    0.039487 -0.000000 -0.015179
   H   1.773996  -0.000000  -0.938711    0.008996 -0.000000  0.022578
converged SCF energy = -114.432663597726
--------------- SymAdaptedRKS_Scanner gradients ---------------
         x                y                z
0 O    -0.0065777350     0.0000000000    -0.0000000000
1 C     0.0066590055     0.0000000000     0.0000000000
2 H    -0.0000965621    -0.0000000000    -0.0020143815
3 H    -0.0000965621     0.0000000000     0.0020143815
----------------------------------------------
cycle 2: E = -114.432663598  dE = -0.000716281  norm(grad) = 0.00978484


Step    1 : Displace = 3.081e-02/4.038e-02 (rms/max) Trust = 1.000e-01 (=) Grad = 4.892e-03/6.659e-03 (rms/max) E (change) = -114.4326635977 (-7.163e-04) Quality = 0.960
Hessian Eigenvalues: 4.50000e-02 4.99292e-02 5.00000e-02 ... 3.08223e-01 3.26001e-01 9.66421e-01



Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.012968   0.000000  -0.023232    0.004839  0.000000 -0.023232
   C   1.188867  -0.000000   0.012673    0.001279 -0.000000  0.012673
   H   1.800284   0.000000   0.952634    0.011043 -0.000000  0.010225
   H   1.777011  -0.000000  -0.942075   -0.012230 -0.000000  0.000335
converged SCF energy = -114.432707967058
--------------- SymAdaptedRKS_Scanner gradients ---------------
         x                y                z
0 O    -0.0004743939     0.0000000000    -0.0000000000
1 C     0.0003999682     0.0000000000     0.0000000000
2 H    -0.0000252906    -0.0000000000    -0.0000916057
3 H    -0.0000252906     0.0000000000     0.0000916057
----------------------------------------------
cycle 3: E = -114.432707967  dE = -4.43693e-05  norm(grad) = 0.000634891


Step    2 : Displace = 4.200e-03/5.357e-03 (rms/max) Trust = 1.414e-01 (+) Grad = 3.174e-04/4.744e-04 (rms/max) E (change) = -114.4327079671 (-4.437e-05) Quality = 1.088
Hessian Eigenvalues: 4.50000e-02 4.92335e-02 5.00000e-02 ... 3.04827e-01 3.26001e-01 9.27875e-01



Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.011291   0.000000  -0.023449    0.001676  0.000000 -0.023449
   C   1.190267   0.000000   0.012648    0.001399  0.000000  0.012648
   H   1.801357   0.000000   0.953015    0.012710  0.000000  0.005660
   H   1.778540  -0.000000  -0.942214   -0.010107 -0.000000  0.005141
converged SCF energy = -114.432708198566
--------------- SymAdaptedRKS_Scanner gradients ---------------
         x                y                z
0 O     0.0000056912     0.0000000000     0.0000000000
1 C    -0.0000717267     0.0000000000    -0.0000000000
2 H    -0.0000298198     0.0000000000     0.0000053939
3 H    -0.0000298198    -0.0000000000    -0.0000053939
----------------------------------------------
cycle 4: E = -114.432708199  dE = -2.31508e-07  norm(grad) = 8.3748e-05


Step    3 : Displace = 2.384e-04/2.867e-04 (rms/max) Trust = 2.000e-01 (+) Grad = 4.187e-05/7.173e-05 (rms/max) E (change) = -114.4327081986 (-2.315e-07) Quality = 0.702
Hessian Eigenvalues: 4.50000e-02 4.92335e-02 5.00000e-02 ... 3.04827e-01 3.26001e-01 9.27875e-01
Converged! =D

    #==========================================================================#
    #| If this code has benefited your research, please support us by citing: |#
    #|                                                                        |#
    #| Wang, L.-P.; Song, C.C. (2016) "Geometry optimization made simple with |#
    #| translation and rotation coordinates", J. Chem, Phys. 144, 214108.     |#
    #| http://dx.doi.org/10.1063/1.4952956                                    |#
    #==========================================================================#
    Time elapsed since start of run_optimizer: 46.936 seconds


In [ ]:
hcoh.set(atom=hcoh_opt_geomtric.tostring())
hcoh.build()
hcoh_opt = dft.RKS(hcoh, xc=func).run()
hess = hcoh_opt.Hessian().kernel()

converged SCF energy = -114.43270819715

WARN: MGGA Hessian is sensitive to dft grids. grids.level 3 may not be dense enough.



In [ ]:
freq_info = thermo.harmonic_analysis(hcoh, hess)
freq_info

{'freq_error': 0,
 'freq_au': array([0.2363558 , 0.24742194, 0.30095488, 0.36124192, 0.55374159,
        0.56170794]),
 'freq_wavenumber': array([1214.98392821, 1271.86929427, 1547.05468891, 1856.95943178,
        2846.50151685, 2887.45242936]),
 'norm_mode': array([[[ 8.50398445e-09, -3.73194999e-02, -2.01705433e-08],
         [ 1.67961775e-09,  1.49314335e-01,  3.63733599e-08],
         [ 8.96379739e-08, -5.93422521e-01, -9.96437148e-09],
         [-2.44627196e-07, -5.93422521e-01, -1.03301408e-07]],
 
        [[-3.20372057e-09,  1.08807458e-08, -6.91959039e-02],
         [ 8.12869259e-09, -4.35335768e-08,  1.29054428e-01],
         [ 5.57240758e-01,  1.73016240e-07, -2.19745687e-01],
         [-5.57240804e-01,  1.73016240e-07, -2.19745847e-01]],
 
        [[-7.39661542e-02, -4.95313574e-09, -5.38195920e-09],
         [ 8.50045587e-04,  1.98173654e-08,  1.34729207e-08],
         [ 5.81931877e-01, -7.87604951e-08, -3.37586930e-01],
         [ 5.81931816e-01, -7.87604950e-08,  3.375868

In [ ]:
thermo_info = thermo.thermo(hcoh_opt, freq_info['freq_au'], 298.15, 101325)
thermo_info

{'temperature': (298.15, 'K'),
 'pressure': (101325, 'Pa'),
 'E0': (np.float64(-114.43270819715036), 'Eh'),
 'S_elec': (np.float64(0.0), 'Eh/K'),
 'Cv_elec': (0, 'Eh/K'),
 'Cp_elec': (0, 'Eh/K'),
 'E_elec': (np.float64(-114.43270819715036), 'Eh'),
 'H_elec': (np.float64(-114.43270819715036), 'Eh'),
 'S_trans': (np.float64(5.757963266472306e-05), 'Eh/K'),
 'Cv_trans': (4.750215777928532e-06, 'Eh/K'),
 'Cp_trans': (7.917026296547553e-06, 'Eh/K'),
 'E_trans': (0.0014162768341893916, 'Eh'),
 'H_trans': (0.0023604613903156525, 'Eh'),
 'rot_const': (array([279.16913518,  38.83026239,  34.08877769]), 'GHz'),
 'sym_number': (2, ''),
 'S_rot': (np.float64(2.5558337513568304e-05), 'Eh/K'),
 'Cv_rot': (4.750215777928532e-06, 'Eh/K'),
 'Cp_rot': (4.750215777928532e-06, 'Eh/K'),
 'E_rot': (0.0014162768341893916, 'Eh'),
 'H_rot': (0.0014162768341893916, 'Eh'),
 'ZPE': (np.float64(0.02648329155468416), 'Eh'),
 'S_vib': (np.float64(1.303570079552929e-07), 'Eh/K'),
 'Cv_vib': (np.float64(7.049732721953

In [ ]:
print(np.sum(freq_info['freq_wavenumber'])/2)
print(thermo_info['ZPE'][0]*219474.63)

5812.410644690801
5812.41061514643


In [ ]:
thermo_info['Cp_tot'][0]*2625.5*1e3

np.float64(35.10875139268587)

In [ ]:
thermo_info['S_tot'][0]*2625.5*1e3

np.float64(218.62099302749058)

In [ ]:
thermo_info['rot_const'][0]/29.9792458

array([9.31208   , 1.29523813, 1.13707923])

In [ ]:
o2 = gto.Mole(atom='O; O 1 1.2', unit='Angstrom', basis='ccpvtz', charge=0, spin=2, symmetry=True)
o2.build()
func = 'MN15_L'
o2_calc = dft.UKS(o2, xc=func).run()
o2_opt_geomtric = o2_calc.Gradients().optimizer(solver='geomeTRIC').kernel()
o2.set(atom=o2_opt_geomtric.tostring())
o2.build()
o2_opt = dft.UKS(o2, xc=func).run()
o2_hess = o2_opt.Hessian().kernel()
freq_info_o2 = thermo.harmonic_analysis(o2, o2_hess)
thermo_info_o2 = thermo.thermo(o2_opt, freq_info_o2['freq_au'], 298.15, 101325)
thermo_info_o2

converged SCF energy = -150.231026502764  <S^2> = 2.0096426  2S+1 = 3.0064215


geometric-optimize called with the following command line:
/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py -f /root/.local/share/jupyter/runtime/kernel-59355ebc-8522-4da2-abea-79e43ea019c1.json

                                        ())))))))))))))))/                     
                                    ())))))))))))))))))))))))),                
                                *)))))))))))))))))))))))))))))))))             
                        #,    ()))))))))/                .)))))))))),          
                      #%%%%,  ())))))                        .))))))))*        
                      *%%%%%%,  ))              ..              ,))))))).      
                        *%%%%%%,         ***************/.        .)))))))     
                #%%/      (%%%%%%,    /*********************.       )))))))    
              .%%%%%%#      *%%%%%%,  *******/,     **********,      .))))))   
                .%%%%%%/      *%%%%%%,  **              ********    


Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O   0.000000   0.000000   0.000000    0.000000  0.000000  0.000000
   O   1.200000   0.000000   0.000000    0.000000  0.000000  0.000000
converged SCF energy = -150.231026502765  <S^2> = 2.0096426  2S+1 = 3.0064215
--------------- SymAdaptedUKS_Scanner gradients ---------------
         x                y                z
0 O     0.0107409464     0.0000000000     0.0000000000
1 O    -0.0107409464     0.0000000000    -0.0000000000
----------------------------------------------
cycle 1: E = -150.231026503  dE = -150.231  norm(grad) = 0.01519


Step    0 : Gradient = 1.074e-02/1.074e-02 (rms/max) Energy = -150.2310265028
Hessian Eigenvalues: 5.00000e-02 5.00000e-02 5.00000e-02 ... 5.00000e-02 5.00000e-02 1.04823e+00



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.002711   0.000000  -0.000000    0.597289  0.000000  0.000000
   O   1.202711   0.000000   0.000000    0.602711  0.000000 -0.000000
converged SCF energy = -150.23108950766  <S^2> = 2.0096961  2S+1 = 3.0064571
--------------- SymAdaptedUKS_Scanner gradients ---------------
         x                y                z
0 O     0.0017081812     0.0000000000     0.0000000000
1 O    -0.0017081812     0.0000000000    -0.0000000000
----------------------------------------------
cycle 2: E = -150.231089508  dE = -6.30049e-05  norm(grad) = 0.00241573


Step    1 : Displace = 2.711e-03/2.711e-03 (rms/max) Trust = 1.000e-01 (=) Grad = 1.708e-03/1.708e-03 (rms/max) E (change) = -150.2310895077 (-6.300e-05) Quality = 1.145
Hessian Eigenvalues: 5.00000e-02 5.00000e-02 5.00000e-02 ... 5.00000e-02 5.00000e-02 8.81526e-01



Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.003224  -0.000000  -0.000000    0.599487 -0.000000  0.000000
   O   1.203224   0.000000   0.000000    0.600513  0.000000 -0.000000
converged SCF energy = -150.231091103028  <S^2> = 2.0097061  2S+1 = 3.0064638
--------------- SymAdaptedUKS_Scanner gradients ---------------
         x                y                z
0 O     0.0000377138     0.0000000000     0.0000000000
1 O    -0.0000377138     0.0000000000    -0.0000000000
----------------------------------------------
cycle 3: E = -150.231091103  dE = -1.59537e-06  norm(grad) = 5.33354e-05


Step    2 : Displace = 5.127e-04/5.127e-04 (rms/max) Trust = 1.414e-01 (+) Grad = 3.771e-05/3.771e-05 (rms/max) E (change) = -150.2310911030 (-1.595e-06) Quality = 0.964
Hessian Eigenvalues: 5.00000e-02 5.00000e-02 5.00000e-02 ... 5.00000e-02 5.00000e-02 8.62063e-01



Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.003235  -0.000000  -0.000000    0.599988 -0.000000  0.000000
   O   1.203235   0.000000   0.000000    0.600012  0.000000 -0.000000
converged SCF energy = -150.23109110171  <S^2> = 2.0097063  2S+1 = 3.0064639
--------------- SymAdaptedUKS_Scanner gradients ---------------
         x                y                z
0 O     0.0000017712     0.0000000000     0.0000000000
1 O    -0.0000017712     0.0000000000    -0.0000000000
----------------------------------------------
cycle 4: E = -150.231091102  dE = 1.31755e-09  norm(grad) = 2.50481e-06


Step    3 : Displace = 1.158e-05/1.158e-05 (rms/max) Trust = 2.000e-01 (+) Grad = 1.771e-06/1.771e-06 (rms/max) E (change) = -150.2310911017 (+1.318e-09) Quality = -1.597
Hessian Eigenvalues: 5.00000e-02 5.00000e-02 5.00000e-02 ... 5.00000e-02 5.00000e-02 8.62063e-01
Converged! =D

    #==========================================================================#
    #| If this code has benefited your research, please support us by citing: |#
    #|                                                                        |#
    #| Wang, L.-P.; Song, C.C. (2016) "Geometry optimization made simple with |#
    #| translation and rotation coordinates", J. Chem, Phys. 144, 214108.     |#
    #| http://dx.doi.org/10.1063/1.4952956                                    |#
    #==========================================================================#
    Time elapsed since start of run_optimizer: 14.546 seconds


converged SCF energy = -150.231091100751  <S^2> = 2.0097064  2S+1 = 3.006464

WARN: MGGA Hessian is sensitive to dft grids. grids.level 3 may not be dense enough.



{'temperature': (298.15, 'K'),
 'pressure': (101325, 'Pa'),
 'E0': (np.float64(-150.23109110075086), 'Eh'),
 'S_elec': (np.float64(3.4790969516382867e-06), 'Eh/K'),
 'Cv_elec': (0, 'Eh/K'),
 'Cp_elec': (0, 'Eh/K'),
 'E_elec': (np.float64(-150.23109110075086), 'Eh'),
 'H_elec': (np.float64(-150.23109110075086), 'Eh'),
 'S_trans': (np.float64(5.78817925976163e-05), 'Eh/K'),
 'Cv_trans': (4.750215777928532e-06, 'Eh/K'),
 'Cp_trans': (7.917026296547553e-06, 'Eh/K'),
 'E_trans': (0.0014162768341893916, 'Eh'),
 'H_trans': (0.0023604613903156525, 'Eh'),
 'rot_const': (array([        inf, 43.40243572, 43.40243572]), 'GHz'),
 'sym_number': (2, ''),
 'S_rot': (np.float64(1.669113597438041e-05), 'Eh/K'),
 'Cv_rot': (3.166810518619021e-06, 'Eh/K'),
 'Cp_rot': (3.166810518619021e-06, 'Eh/K'),
 'E_rot': (0.0009441845561262611, 'Eh'),
 'H_rot': (0.0009441845561262611, 'Eh'),
 'ZPE': (np.float64(0.0038093565737536625), 'Eh'),
 'S_vib': (np.float64(8.993977457331009e-09), 'Eh/K'),
 'Cv_vib': (np.float6

In [ ]:
sacasscf = mcscf.CASSCF(scf.ROHF(o2).run(), 6, 8).state_average_([0.25, 0.25, 0.25, 0.25]).run()

converged SCF energy = -149.653987187931

WARN: QR decomposition removed 2 vectors.

CASSCF energy = -149.095442733767
CASCI E = -149.095442733767  E(CI) = -20.2253307520337  S^2 = 3.0000000
CASCI state-averaged energy = -149.095442733767
CASCI energy for each state
  State 0 weight 0.25  E = -149.727752251401 S^2 = 2.0000000
  State 1 weight 0.25  E = -149.120962743299 S^2 = 2.0000000
  State 2 weight 0.25  E = -148.893357666861 S^2 = 2.0000000
  State 3 weight 0.25  E = -148.639698273507 S^2 = 6.0000000


In [ ]:
hcoh_exc = hcoh_opt.TDDFT().run()
hcoh_exc.analyze(verbose=4)

Excited State energies (eV)
[4.8001972  7.83624284 9.52075499]

** Singlet excitation energies and oscillator strengths **
Excited State   1:   A2      4.80020 eV    258.29 nm  f=0.0000
       8 -> 9        -0.70702
Excited State   2:   B2      7.83624 eV    158.22 nm  f=0.1391
       8 -> 10       -0.70536
Excited State   3:   A1      9.52075 eV    130.23 nm  f=0.0164
       7 -> 9        -0.37646
       8 -> 11       -0.59362

** Transition electric dipole moments (AU) **
state          X           Y           Z        Dip. S.      Osc.
  1         0.0000      0.0000     -0.0000      0.0000      0.0000
  2        -0.0000     -0.0000     -0.8513      0.7248      0.1391
  3         0.2650      0.0000      0.0000      0.0702      0.0164

** Transition velocity dipole moments (imaginary part, AU) **
state          X           Y           Z        Dip. S.      Osc.
  1         0.0000      0.0000     -0.0000      0.0000      0.0000
  2        -0.0000     -0.0000     -0.2091      0.0437    

In [ ]:
hcoh_ccsd = cc.CCSD(scf.RHF(hcoh).run()).run(verbose=4)

converged SCF energy = -113.911044824607

******** <class 'pyscf.cc.ccsd.CCSD'> ********
CC2 = 0
CCSD nocc = 8, nmo = 88
max_cycle = 50
direct = 0
conv_tol = 1e-07
conv_tol_normt = 1e-05
diis_space = 6
diis_start_cycle = 0
diis_start_energy_diff = 1e+09
max_memory 4000 MB (current use 464 MB)
Init t2, MP2 energy = -114.33450938835  E_corr(MP2) -0.423464563742482
Init E_corr(CCSD) = -0.423464563742669
cycle = 1  E_corr(CCSD) = -0.419491486906907  dE = 0.00397307684  norm(t1,t2) = 0.0541326
cycle = 2  E_corr(CCSD) = -0.432676569269572  dE = -0.0131850824  norm(t1,t2) = 0.0206545
cycle = 3  E_corr(CCSD) = -0.432233237497841  dE = 0.000443331772  norm(t1,t2) = 0.0105472
cycle = 4  E_corr(CCSD) = -0.433843502183764  dE = -0.00161026469  norm(t1,t2) = 0.00451046
cycle = 5  E_corr(CCSD) = -0.434046517553031  dE = -0.000203015369  norm(t1,t2) = 0.00109102
cycle = 6  E_corr(CCSD) = -0.4339159568113  dE = 0.000130560742  norm(t1,t2) = 0.000390268
cycle = 7  E_corr(CCSD) = -0.433902089487796  dE 

In [ ]:
hcoh_ccsd.eeccsd(nroots=3)


******** <class 'pyscf.cc.eom_rccsd.EOMEESinglet'> ********
max_space = 20
max_cycle = 50
conv_tol = 1e-07
partition = None
max_memory 4000 MB (current use 640 MB)
EOM-CCSD root 0 E = 0.1510436390838105  qpwt = 0.939041  conv = True

******** <class 'pyscf.cc.eom_rccsd.EOMEETriplet'> ********
max_space = 20
max_cycle = 50
conv_tol = 1e-07
partition = None
max_memory 4000 MB (current use 662 MB)
EOM-CCSD root 0 E = 0.1340530793019163  qpwt = 0.945494  conv = True

******** <class 'pyscf.cc.eom_rccsd.EOMEESpinFlip'> ********
max_space = 20
max_cycle = 50
conv_tol = 1e-07
partition = None
max_memory 4000 MB (current use 626 MB)
EOM-CCSD root 0 E = 0.1340530716519335  qpwt = 0.945494  conv = True


(array([0.13405307, 0.13405307, 0.13405308, 0.15104364]),
 [None,
  array([-5.60037429e-19,  1.01737652e-21, -1.66742320e-34, ...,
          4.03936084e-05,  3.17216030e-04,  5.02234628e-05]),
  array([ 5.58951057e-19, -1.05071673e-21,  1.41188843e-34, ...,
          3.85420075e-21, -1.62400728e-20,  0.00000000e+00]),
  array([-1.87583198e-19,  1.02494082e-21,  6.17399535e-34, ...,
         -8.64028709e-21, -3.77122931e-20,  3.09489156e-21])])

In [ ]:
hcoh_ccsd.eomsf_ccsd(nroots=3)


******** <class 'pyscf.cc.eom_rccsd.EOMEESpinFlip'> ********
max_space = 20
max_cycle = 50
conv_tol = 1e-07
partition = None
max_memory 4000 MB (current use 542 MB)
EOM-CCSD root 0 E = 0.134053144380455  qpwt = 0.945494  conv = True
EOM-CCSD root 1 E = 0.2237379660064363  qpwt = 0.968937  conv = True
EOM-CCSD root 2 E = 0.2849564909512883  qpwt = 0.936906  conv = True


(array([0.13405314, 0.22373797, 0.28495649]),
 [array([-4.83171466e-18,  1.09449327e-21, -8.10023166e-21, ...,
          4.03904893e-05,  3.17203829e-04,  5.02195281e-05]),
  array([ 6.06012674e-32,  4.50600541e-06,  2.36688793e-18, ...,
         -2.31529283e-20,  2.69088143e-19,  3.85752722e-20]),
  array([-2.72614977e-21,  2.83301667e-17,  2.96332504e-05, ...,
          1.23451366e-19, -3.45801036e-20,  2.99969306e-19])])

In [ ]:
np.array([0.13413078, 0.22450117, 0.28763019])*27.2*8065.54

array([29425.97105994, 49251.67013374, 63101.08423215])

In [ ]:
exc_grad = hcoh_exc.nuc_grad_method().as_scanner(state=1)
hcoh_exc_opt = exc_grad.optimizer().kernel()

geometric-optimize called with the following command line:
/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py -f /root/.local/share/jupyter/runtime/kernel-59355ebc-8522-4da2-abea-79e43ea019c1.json

                                        ())))))))))))))))/                     
                                    ())))))))))))))))))))))))),                
                                *)))))))))))))))))))))))))))))))))             
                        #,    ()))))))))/                .)))))))))),          
                      #%%%%,  ())))))                        .))))))))*        
                      *%%%%%%,  ))              ..              ,))))))).      
                        *%%%%%%,         ***************/.        .)))))))     
                #%%/      (%%%%%%,    /*********************.       )))))))    
              .%%%%%%#      *%%%%%%,  *******/,     **********,      .))))))   
                .%%%%%%/      *%%%%%%,  **              ********    


Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.011290   0.000000   0.000000    0.000000  0.000000  0.000000
   C   1.190270   0.000000   0.000000    0.000000  0.000000  0.000000
   H   1.789950   0.000000   0.947610    0.000000  0.000000  0.000000
   H   1.789950   0.000000  -0.947610    0.000000  0.000000  0.000000
converged SCF energy = -114.432708197143
Excited State energies (eV)
[4.80020123 7.83624907 9.52076073]

WARN: TDRKS-MGGA Gradients may be inaccurate due to grids response


WARN: TDRKS-MGGA Gradients may be inaccurate due to grids response

--------- CasidaTDDFT_Scanner gradients for state 1 ----------
         x                y                z
0 O     0.1229473883     0.0000000000     0.0000000000
1 C    -0.1310488072     0.0000000000    -0.0000000000
2 H     0.0040185067     0.0000000000     0.0054942861
3 H     0.0040185067    -0.0000000000    -0.0054942861
----------------------

Step    0 : Gradient = 8.998e-02/1.310e-01 (rms/max) Energy = -114.2563040541
Hessian Eigenvalues: 4.50000e-02 5.00000e-02 5.00000e-02 ... 3.14203e-01 3.14203e-01 1.04043e+00



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.052985  -0.000000   0.001489   -0.041695 -0.000000  0.001489
   C   1.211114   0.000000  -0.000962    0.020844  0.000000 -0.000962
   H   1.800628   0.000000   0.939516    0.010678  0.000000 -0.008094
   H   1.802850   0.000000  -0.940043    0.012900  0.000000  0.007567
converged SCF energy = -114.427129692774
Excited State energies (eV)
[4.40043073 7.89455935 9.05022603]

WARN: TDRKS-MGGA Gradients may be inaccurate due to grids response


WARN: TDRKS-MGGA Gradients may be inaccurate due to grids response

--------- CasidaTDDFT_Scanner gradients for state 1 ----------
         x                y                z
0 O     0.0325834039     0.0000000000     0.0000000000
1 C    -0.0441383955     0.0000000000    -0.0000000000
2 H     0.0057566843     0.0000000000     0.0012129716
3 H     0.0057566843    -0.0000000000    -0.0012129716
----------------------

Step    1 : Displace = 2.538e-02/4.240e-02 (rms/max) Trust = 1.000e-01 (=) Grad = 2.774e-02/4.414e-02 (rms/max) E (change) = -114.2654168447 (-9.113e-03) Quality = 1.229
Hessian Eigenvalues: 4.50000e-02 4.99991e-02 5.00000e-02 ... 3.05352e-01 3.14203e-01 7.94247e-01



Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.051361  -0.000000   0.018218    0.001623 -0.000000  0.018218
   C   1.239208  -0.000000  -0.012323    0.028095 -0.000000 -0.012323
   H   1.771933  -0.000000   0.949768   -0.029806 -0.000000  0.009989
   H   1.804430  -0.000000  -0.955663    0.002691 -0.000000 -0.015884
converged SCF energy = -114.421989386253
Excited State energies (eV)
[4.21920317 7.90485679 8.7801078 ]

WARN: TDRKS-MGGA Gradients may be inaccurate due to grids response


WARN: TDRKS-MGGA Gradients may be inaccurate due to grids response

--------- CasidaTDDFT_Scanner gradients for state 1 ----------
         x                y                z
0 O     0.0084935462     0.0000000000     0.0000000000
1 C    -0.0101875402     0.0000000000    -0.0000000000
2 H     0.0008315431    -0.0000000000    -0.0007449412
3 H     0.0008315431     0.0000000000     0.0007449412
----------------------

Step    2 : Displace = 2.434e-02/2.998e-02 (rms/max) Trust = 1.414e-01 (+) Grad = 6.679e-03/1.019e-02 (rms/max) E (change) = -114.2669365282 (-1.520e-03) Quality = 1.221
Hessian Eigenvalues: 4.50000e-02 4.99499e-02 5.00000e-02 ... 3.10851e-01 3.14206e-01 6.85754e-01



Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.051418  -0.000000   0.018701   -0.000057 -0.000000  0.018701
   C   1.248093  -0.000000  -0.015067    0.008885 -0.000000 -0.015067
   H   1.761191  -0.000000   0.956957   -0.026990 -0.000000  0.004241
   H   1.808341  -0.000000  -0.960590    0.020159 -0.000000 -0.007875
converged SCF energy = -114.419870771983
Excited State energies (eV)
[4.15863873 7.89206747 8.68129386]

WARN: TDRKS-MGGA Gradients may be inaccurate due to grids response


WARN: TDRKS-MGGA Gradients may be inaccurate due to grids response

--------- CasidaTDDFT_Scanner gradients for state 1 ----------
         x                y                z
0 O     0.0008909164     0.0000000000     0.0000000000
1 C    -0.0007634185     0.0000000000    -0.0000000000
2 H    -0.0000698230    -0.0000000000    -0.0000980286
3 H    -0.0000698230     0.0000000000     0.0000980286
----------------------

Step    3 : Displace = 7.763e-03/9.399e-03 (rms/max) Trust = 2.000e-01 (+) Grad = 5.928e-04/8.909e-04 (rms/max) E (change) = -114.2670436161 (-1.071e-04) Quality = 1.071
Hessian Eigenvalues: 4.50000e-02 4.98645e-02 5.00000e-02 ... 3.11221e-01 3.14206e-01 6.37874e-01



Geometry optimization cycle 5
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.051741  -0.000000   0.018317   -0.000323 -0.000000  0.018317
   C   1.248626  -0.000000  -0.015074    0.000533 -0.000000 -0.015074
   H   1.761009  -0.000000   0.957466   -0.023758 -0.000000 -0.001307
   H   1.808924  -0.000000  -0.960710    0.024158 -0.000000 -0.001937
converged SCF energy = -114.419675985216
Excited State energies (eV)
[4.1533363  7.89087696 8.67133665]

WARN: TDRKS-MGGA Gradients may be inaccurate due to grids response


WARN: TDRKS-MGGA Gradients may be inaccurate due to grids response

--------- CasidaTDDFT_Scanner gradients for state 1 ----------
         x                y                z
0 O     0.0000822797     0.0000000000     0.0000000000
1 C    -0.0000514214     0.0000000000    -0.0000000000
2 H    -0.0000211057     0.0000000000     0.0000092933
3 H    -0.0000211057    -0.0000000000    -0.0000092933
----------------------

Step    4 : Displace = 3.815e-04/4.721e-04 (rms/max) Trust = 2.828e-01 (+) Grad = 5.118e-05/8.228e-05 (rms/max) E (change) = -114.2670436900 (-7.390e-08) Quality = 0.100
Hessian Eigenvalues: 4.50000e-02 4.98645e-02 5.00000e-02 ... 3.11221e-01 3.14206e-01 6.37874e-01
Converged! =D

    #==========================================================================#
    #| If this code has benefited your research, please support us by citing: |#
    #|                                                                        |#
    #| Wang, L.-P.; Song, C.C. (2016) "Geometry optimization made simple with |#
    #| translation and rotation coordinates", J. Chem, Phys. 144, 214108.     |#
    #| http://dx.doi.org/10.1063/1.4952956                                    |#
    #==========================================================================#
    Time elapsed since start of run_optimizer: 293.738 seconds


In [ ]:
hcoh.set(atom=hcoh_exc_opt.tostring())
hcoh.build()
hcoh_exc_ccsd = cc.CCSD(scf.RHF(hcoh).run()).run(verbose=4)
hcoh_exc_ccsd.eomsf_ccsd(nroots=3)

converged SCF energy = -113.891065740103

******** <class 'pyscf.cc.ccsd.CCSD'> ********
CC2 = 0
CCSD nocc = 8, nmo = 88
max_cycle = 50
direct = 0
conv_tol = 1e-07
conv_tol_normt = 1e-05
diis_space = 6
diis_start_cycle = 0
diis_start_energy_diff = 1e+09
max_memory 4000 MB (current use 674 MB)
Init t2, MP2 energy = -114.324684793332  E_corr(MP2) -0.433619053229244
Init E_corr(CCSD) = -0.433619053230222
cycle = 1  E_corr(CCSD) = -0.424288309924656  dE = 0.00933074331  norm(t1,t2) = 0.0634887
cycle = 2  E_corr(CCSD) = -0.440662456389775  dE = -0.0163741465  norm(t1,t2) = 0.0268697
cycle = 3  E_corr(CCSD) = -0.439466904072813  dE = 0.00119555232  norm(t1,t2) = 0.0146787
cycle = 4  E_corr(CCSD) = -0.44143840457107  dE = -0.0019715005  norm(t1,t2) = 0.00644902
cycle = 5  E_corr(CCSD) = -0.441841744485599  dE = -0.000403339915  norm(t1,t2) = 0.00175899
cycle = 6  E_corr(CCSD) = -0.441627433437629  dE = 0.000214311048  norm(t1,t2) = 0.000609552
cycle = 7  E_corr(CCSD) = -0.441605230746064  dE 

(array([0.11003543, 0.17048266, 0.27142191]),
 [array([ 8.78818503e-19, -2.00984732e-20, -1.13847950e-32, ...,
          4.78395764e-06, -1.78322946e-04,  1.13094261e-04]),
  array([ 2.54724819e-18,  1.66163507e-06, -1.09239209e-18, ...,
          1.64635256e-19,  1.22611887e-19,  7.30270664e-19]),
  array([-3.76379712e-04, -4.20365209e-21,  3.57433388e-20, ...,
         -2.26589438e-19,  1.34951962e-18,  4.22255261e-19])])

In [ ]:
0.10857223*27.2*8066

23820.226115296

Д/з до 10.04.2025


1.   Определить колебательные частоты молекулы из Д/з №2 и №3 с теми же 3 базисными наборами и теми же самыми функционалами плотности. Сравнить результаты расчетов с экспериментальными данными и время выполнения.
2.   Определить для этой же молекулы вертикальные энергии возбуждения (без изменения геометрии) методами TDDFT и EOM-CCSD любым из 3 базисных наборов


Примечание: в теме письма с домашней работой указать свою фамилию и номер группы